/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as OndeEstamosRouteImport } from './routes/onde-estamos'
import { Route as MeusPedidosRouteImport } from './routes/meus-pedidos'
import { Route as MesaRouteImport } from './routes/mesa'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ExcluirDadosRouteImport } from './routes/excluir-dados'
import { Route as CheckoutMesaRouteImport } from './routes/checkout-mesa'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AcompanharRouteImport } from './routes/acompanhar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcompanharIdRouteImport } from './routes/acompanhar.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeEstamosRoute = OndeEstamosRouteImport.update({
  id: '/onde-estamos',
  path: '/onde-estamos',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusPedidosRoute = MeusPedidosRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MesaRoute = MesaRouteImport.update({
  id: '/mesa',
  path: '/mesa',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcluirDadosRoute = ExcluirDadosRouteImport.update({
  id: '/excluir-dados',
  path: '/excluir-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutMesaRoute = CheckoutMesaRouteImport.update({
  id: '/checkout-mesa',
  path: '/checkout-mesa',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharRoute = AcompanharRouteImport.update({
  id: '/acompanhar',
  path: '/acompanhar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharIdRoute = AcompanharIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AcompanharRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/checkout-mesa': typeof CheckoutMesaRoute
  '/excluir-dados': typeof ExcluirDadosRoute
  '/menu': typeof MenuRoute
  '/mesa': typeof MesaRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/onde-estamos': typeof OndeEstamosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/acompanhar/$id': typeof AcompanharIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/checkout-mesa': typeof CheckoutMesaRoute
  '/excluir-dados': typeof ExcluirDadosRoute
  '/menu': typeof MenuRoute
  '/mesa': typeof MesaRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/onde-estamos': typeof OndeEstamosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/acompanhar/$id': typeof AcompanharIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/checkout-mesa': typeof CheckoutMesaRoute
  '/excluir-dados': typeof ExcluirDadosRoute
  '/menu': typeof MenuRoute
  '/mesa': typeof MesaRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/onde-estamos': typeof OndeEstamosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/acompanhar/$id': typeof AcompanharIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhar'
    | '/checkout'
    | '/checkout-mesa'
    | '/excluir-dados'
    | '/menu'
    | '/mesa'
    | '/meus-pedidos'
    | '/onde-estamos'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/acompanhar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acompanhar'
    | '/checkout'
    | '/checkout-mesa'
    | '/excluir-dados'
    | '/menu'
    | '/mesa'
    | '/meus-pedidos'
    | '/onde-estamos'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/acompanhar/$id'
  id:
    | '__root__'
    | '/'
    | '/acompanhar'
    | '/checkout'
    | '/checkout-mesa'
    | '/excluir-dados'
    | '/menu'
    | '/mesa'
    | '/meus-pedidos'
    | '/onde-estamos'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/acompanhar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcompanharRoute: typeof AcompanharRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  CheckoutMesaRoute: typeof CheckoutMesaRoute
  ExcluirDadosRoute: typeof ExcluirDadosRoute
  MenuRoute: typeof MenuRoute
  MesaRoute: typeof MesaRoute
  MeusPedidosRoute: typeof MeusPedidosRoute
  OndeEstamosRoute: typeof OndeEstamosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-estamos': {
      id: '/onde-estamos'
      path: '/onde-estamos'
      fullPath: '/onde-estamos'
      preLoaderRoute: typeof OndeEstamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-pedidos': {
      id: '/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof MeusPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesa': {
      id: '/mesa'
      path: '/mesa'
      fullPath: '/mesa'
      preLoaderRoute: typeof MesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excluir-dados': {
      id: '/excluir-dados'
      path: '/excluir-dados'
      fullPath: '/excluir-dados'
      preLoaderRoute: typeof ExcluirDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-mesa': {
      id: '/checkout-mesa'
      path: '/checkout-mesa'
      fullPath: '/checkout-mesa'
      preLoaderRoute: typeof CheckoutMesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar': {
      id: '/acompanhar'
      path: '/acompanhar'
      fullPath: '/acompanhar'
      preLoaderRoute: typeof AcompanharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar/$id': {
      id: '/acompanhar/$id'
      path: '/$id'
      fullPath: '/acompanhar/$id'
      preLoaderRoute: typeof AcompanharIdRouteImport
      parentRoute: typeof AcompanharRoute
    }
  }
}

interface AcompanharRouteChildren {
  AcompanharIdRoute: typeof AcompanharIdRoute
}

const AcompanharRouteChildren: AcompanharRouteChildren = {
  AcompanharIdRoute: AcompanharIdRoute,
}

const AcompanharRouteWithChildren = AcompanharRoute._addFileChildren(
  AcompanharRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcompanharRoute: AcompanharRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  CheckoutMesaRoute: CheckoutMesaRoute,
  ExcluirDadosRoute: ExcluirDadosRoute,
  MenuRoute: MenuRoute,
  MesaRoute: MesaRoute,
  MeusPedidosRoute: MeusPedidosRoute,
  OndeEstamosRoute: OndeEstamosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
