/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EntregadorRouteImport } from './routes/entregador'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EntregaDriverIdRouteImport } from './routes/entrega.$driverId'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminMesasRouteImport } from './routes/admin.mesas'
import { Route as AdminFinalizadosRouteImport } from './routes/admin.finalizados'
import { Route as AdminEntregadoresRouteImport } from './routes/admin.entregadores'
import { Route as AdminEntregaRouteImport } from './routes/admin.entrega'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCardapioRouteImport } from './routes/admin.cardapio'
import { Route as AdminPedidosIndexRouteImport } from './routes/admin.pedidos.index'
import { Route as AdminPedidosIdRouteImport } from './routes/admin.pedidos.$id'

const EntregadorRoute = EntregadorRouteImport.update({
  id: '/entregador',
  path: '/entregador',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EntregaDriverIdRoute = EntregaDriverIdRouteImport.update({
  id: '/entrega/$driverId',
  path: '/entrega/$driverId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMesasRoute = AdminMesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinalizadosRoute = AdminFinalizadosRouteImport.update({
  id: '/finalizados',
  path: '/finalizados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntregadoresRoute = AdminEntregadoresRouteImport.update({
  id: '/entregadores',
  path: '/entregadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntregaRoute = AdminEntregaRouteImport.update({
  id: '/entrega',
  path: '/entrega',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardapioRoute = AdminCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosIndexRoute = AdminPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosIdRoute = AdminPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/entregador': typeof EntregadorRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/entrega': typeof AdminEntregaRoute
  '/admin/entregadores': typeof AdminEntregadoresRoute
  '/admin/finalizados': typeof AdminFinalizadosRoute
  '/admin/mesas': typeof AdminMesasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/entrega/$driverId': typeof EntregaDriverIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entregador': typeof EntregadorRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/entrega': typeof AdminEntregaRoute
  '/admin/entregadores': typeof AdminEntregadoresRoute
  '/admin/finalizados': typeof AdminFinalizadosRoute
  '/admin/mesas': typeof AdminMesasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/entrega/$driverId': typeof EntregaDriverIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/pedidos': typeof AdminPedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/entregador': typeof EntregadorRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/entrega': typeof AdminEntregaRoute
  '/admin/entregadores': typeof AdminEntregadoresRoute
  '/admin/finalizados': typeof AdminFinalizadosRoute
  '/admin/mesas': typeof AdminMesasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/entrega/$driverId': typeof EntregaDriverIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/entregador'
    | '/admin/cardapio'
    | '/admin/configuracoes'
    | '/admin/entrega'
    | '/admin/entregadores'
    | '/admin/finalizados'
    | '/admin/mesas'
    | '/admin/usuarios'
    | '/entrega/$driverId'
    | '/admin/'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entregador'
    | '/admin/cardapio'
    | '/admin/configuracoes'
    | '/admin/entrega'
    | '/admin/entregadores'
    | '/admin/finalizados'
    | '/admin/mesas'
    | '/admin/usuarios'
    | '/entrega/$driverId'
    | '/admin'
    | '/admin/pedidos/$id'
    | '/admin/pedidos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/entregador'
    | '/admin/cardapio'
    | '/admin/configuracoes'
    | '/admin/entrega'
    | '/admin/entregadores'
    | '/admin/finalizados'
    | '/admin/mesas'
    | '/admin/usuarios'
    | '/entrega/$driverId'
    | '/admin/'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EntregadorRoute: typeof EntregadorRoute
  EntregaDriverIdRoute: typeof EntregaDriverIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/entregador': {
      id: '/entregador'
      path: '/entregador'
      fullPath: '/entregador'
      preLoaderRoute: typeof EntregadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/entrega/$driverId': {
      id: '/entrega/$driverId'
      path: '/entrega/$driverId'
      fullPath: '/entrega/$driverId'
      preLoaderRoute: typeof EntregaDriverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mesas': {
      id: '/admin/mesas'
      path: '/mesas'
      fullPath: '/admin/mesas'
      preLoaderRoute: typeof AdminMesasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finalizados': {
      id: '/admin/finalizados'
      path: '/finalizados'
      fullPath: '/admin/finalizados'
      preLoaderRoute: typeof AdminFinalizadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entregadores': {
      id: '/admin/entregadores'
      path: '/entregadores'
      fullPath: '/admin/entregadores'
      preLoaderRoute: typeof AdminEntregadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entrega': {
      id: '/admin/entrega'
      path: '/entrega'
      fullPath: '/admin/entrega'
      preLoaderRoute: typeof AdminEntregaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cardapio': {
      id: '/admin/cardapio'
      path: '/cardapio'
      fullPath: '/admin/cardapio'
      preLoaderRoute: typeof AdminCardapioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/': {
      id: '/admin/pedidos/'
      path: '/pedidos'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AdminPedidosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCardapioRoute: typeof AdminCardapioRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEntregaRoute: typeof AdminEntregaRoute
  AdminEntregadoresRoute: typeof AdminEntregadoresRoute
  AdminFinalizadosRoute: typeof AdminFinalizadosRoute
  AdminMesasRoute: typeof AdminMesasRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPedidosIdRoute: typeof AdminPedidosIdRoute
  AdminPedidosIndexRoute: typeof AdminPedidosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCardapioRoute: AdminCardapioRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEntregaRoute: AdminEntregaRoute,
  AdminEntregadoresRoute: AdminEntregadoresRoute,
  AdminFinalizadosRoute: AdminFinalizadosRoute,
  AdminMesasRoute: AdminMesasRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPedidosIdRoute: AdminPedidosIdRoute,
  AdminPedidosIndexRoute: AdminPedidosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EntregadorRoute: EntregadorRoute,
  EntregaDriverIdRoute: EntregaDriverIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
